// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace main.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926013749_InicialConexionBackend")]
    partial class InicialConexionBackend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("main.Models.Alerta", b =>
                {
                    b.Property<int>("Id_alerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_alerta"));

                    b.Property<DateTime>("fecha_horario")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nivel_urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id_alerta");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("main.Models.Barrio", b =>
                {
                    b.Property<int>("Id_barrio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_barrio"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_barrio");

                    b.ToTable("Barrios");
                });

            modelBuilder.Entity("main.Models.Barrio_Alerta", b =>
                {
                    b.Property<int>("Id_barrio_alerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_barrio_alerta"));

                    b.Property<int>("Id_alerta")
                        .HasColumnType("int");

                    b.Property<int>("Id_barrio")
                        .HasColumnType("int");

                    b.HasKey("Id_barrio_alerta");

                    b.HasIndex("Id_alerta");

                    b.HasIndex("Id_barrio");

                    b.ToTable("AlertasBarrios");
                });

            modelBuilder.Entity("main.Models.Ciudadano", b =>
                {
                    b.Property<int>("Id_ciudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_ciudadano"));

                    b.Property<int>("Id_barrio")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_ciudadano");

                    b.HasIndex("Id_barrio");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.ToTable("Ciudadanos");
                });

            modelBuilder.Entity("main.Models.Reporte", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_modificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_reporte");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("main.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id_ubicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_ubicacion"));

                    b.Property<int>("Id_reporte")
                        .HasColumnType("int");

                    b.Property<int>("altura")
                        .HasColumnType("int");

                    b.Property<string>("calle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("informacion_adicional")
                        .HasColumnType("longtext");

                    b.Property<int>("latitud")
                        .HasColumnType("int");

                    b.HasKey("Id_ubicacion");

                    b.HasIndex("Id_reporte")
                        .IsUnique();

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("main.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<int>("Id_ciudadano")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("constrasenia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("es_admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_usuario");

                    b.HasIndex("Id_ciudadano")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("main.Models.Barrio_Alerta", b =>
                {
                    b.HasOne("main.Models.Alerta", "Alerta")
                        .WithMany("BarriosAlertas")
                        .HasForeignKey("Id_alerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("main.Models.Barrio", "Barrio")
                        .WithMany("BarrioAlertas")
                        .HasForeignKey("Id_barrio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Barrio");
                });

            modelBuilder.Entity("main.Models.Ciudadano", b =>
                {
                    b.HasOne("main.Models.Barrio", "Barrio")
                        .WithMany("Ciudadanos")
                        .HasForeignKey("Id_barrio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barrio");
                });

            modelBuilder.Entity("main.Models.Reporte", b =>
                {
                    b.HasOne("main.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("main.Models.Ubicacion", b =>
                {
                    b.HasOne("main.Models.Reporte", "Reporte")
                        .WithOne("Ubicacion")
                        .HasForeignKey("main.Models.Ubicacion", "Id_reporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("main.Models.Usuario", b =>
                {
                    b.HasOne("main.Models.Ciudadano", "Ciudadano")
                        .WithOne("Usuario")
                        .HasForeignKey("main.Models.Usuario", "Id_ciudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudadano");
                });

            modelBuilder.Entity("main.Models.Alerta", b =>
                {
                    b.Navigation("BarriosAlertas");
                });

            modelBuilder.Entity("main.Models.Barrio", b =>
                {
                    b.Navigation("BarrioAlertas");

                    b.Navigation("Ciudadanos");
                });

            modelBuilder.Entity("main.Models.Ciudadano", b =>
                {
                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("main.Models.Reporte", b =>
                {
                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("main.Models.Usuario", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
